#!/bin/bash
while read -r line; do fields=( $(echo "$line" | tr '\t' ' ') ) host="$fields[0]" host_counts[$host] += 1 done < "$1" sorted_hosts=$(for host in "${!host_counts[@]}"; do echo "${host} ${host_counts[$host]}" done | sort -n -k 2 -r | head -n 11) echo "$sorted_hosts"
